# Generated by Django 3.1.3 on 2020-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subdirectory",
            field=models.FilePathField(
                allow_folders=True, default="/data/", path="/data", recursive=True
            ),
        ),
    ]
