# Generated by Django 3.1.3 on 2020-11-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Photo creation time.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True, help_text="Photo modification time.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo_taken_time",
            field=models.DateTimeField(
                blank=True, help_text="Time the photo was taken.", null=True
            ),
        ),
    ]
