# Generated by Django 3.1.3 on 2020-11-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_auto_20201128_2159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.FilePathField(
                help_text="Path to the photo file.", path="/data"
            ),
        ),
    ]
