# Generated by Django 3.1.4 on 2020-12-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faces", "__first__"),
        ("photos", "0002_auto_20201209_0457"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="faces",
            field=models.ManyToManyField(blank=True, to="faces.Face"),
        ),
    ]
