# Generated by Django 3.1.6 on 2021-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_photo_faces"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="file_type",
            field=models.IntegerField(choices=[(1, "Image"), (2, "Video")], default=1),
        ),
    ]
