# Generated by Django 3.1.3 on 2020-11-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0006_auto_20201128_2213"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                default=None,
                help_text="The user that this photo belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
            preserve_default=False,
        ),
    ]
