# Generated by Django 3.1.3 on 2020-11-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0007_photo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="aperture_value",
            field=models.FloatField(help_text="Aperture in the APEX system", null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="camera_make",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="photo",
            name="camera_model",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="photo",
            name="flash_fired",
            field=models.BooleanField(help_text="Did the flash fire?", null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="flash_mode",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Compulsory Flash Firing"),
                    (2, "Compulsory Flash Suppression"),
                    (3, "Automatic"),
                ],
                help_text="Flash firing mode",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="focal_length",
            field=models.FloatField(help_text="Focal length in millimeters", null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_height",
            field=models.PositiveIntegerField(
                help_text="Height, in pixels, of the image", null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_size",
            field=models.PositiveIntegerField(
                help_text="File size (on disk) of the image", null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_width",
            field=models.PositiveIntegerField(
                help_text="Width, in pixels, of the image", null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="iso",
            field=models.PositiveIntegerField(
                help_text="Sensor sensitivity in ISO", null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="shutter_speed_value",
            field=models.FloatField(
                help_text="Shutter speed in the APEX system", null=True
            ),
        ),
    ]
