# Generated by Django 3.1.3 on 2020-11-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0008_auto_20201128_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="iso",
            field=models.PositiveIntegerField(
                help_text="Sensor sensitivity in ISO", null=True, verbose_name="ISO"
            ),
        ),
    ]
