# Generated by Django 3.1.3 on 2020-11-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0009_auto_20201128_2351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_size",
            field=models.PositiveIntegerField(
                help_text="File size (on disk, in bytes) of the image", null=True
            ),
        ),
    ]
