# Generated by Django 3.1.3 on 2020-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0011_auto_20201129_2034"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="license",
            field=models.CharField(
                choices=[
                    ("ARR", "All rights reserved"),
                    ("PDM", "Public Domain Mark"),
                    ("CC0", "CC0"),
                    ("CCBY", "Creative Commons Attribution"),
                    ("CCBYSA", "Creative Commons Attribution Share-Alike"),
                    ("CCBYND", "Creative Commons Attribution-NoDerivs"),
                    ("CCBYNC", "Creative Commons Attribution-NonCommercial"),
                    (
                        "CCBYNCSA",
                        "Creative Commons Attribution-NonCommercial-ShareAlike",
                    ),
                    ("CCBYNCND", "Creative Commons Attribution-NonCommercial-NoDerivs"),
                ],
                default="ARR",
                max_length=50,
            ),
        ),
    ]
