# Generated by Django 3.1.3 on 2020-11-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0012_photo_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="publicly_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether this photo is publicly accessible. If checked, this photo islisted on the front page and accessible without authentication.",
            ),
        ),
    ]
