# Generated by Django 3.1.4 on 2020-12-04 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0014_auto_20201201_0114"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoTag",
            fields=[
                (
                    "slug",
                    models.SlugField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(to="photos.PhotoTag"),
        ),
    ]
