# Generated by Django 3.1.4 on 2020-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0015_auto_20201204_2241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="photos.PhotoTag"),
        ),
    ]
