# Generated by Django 3.1.4 on 2020-12-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0016_auto_20201204_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phototag",
            name="slug",
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
