# Generated by Django 3.1.4 on 2020-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("photos", "0019_phototag_is_auto_generated"),
    ]

    database_operations = [
        migrations.AlterModelTable(
            name="PhotoTag",
            table="tags_phototag",
        ),
        migrations.AlterField(
            model_name="photo",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.PhotoTag"),
        ),
    ]

    state_operations = [
        migrations.DeleteModel(
            name="PhotoTag",
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
    ]
