# Generated by Django 3.1.3 on 2020-11-29 18:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0010_auto_20201129_0228"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name for this album.", max_length=300),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description for this album."
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Album creation time.", null=True
                    ),
                ),
                (
                    "last_modified_time",
                    models.DateTimeField(
                        auto_now=True, help_text="Album modification time.", null=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user that this album belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("photos", models.ManyToManyField(to="photos.Photo")),
            ],
        ),
    ]
