# Generated by Django 3.1.3 on 2020-11-29 20:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Album share link creation time.",
                        null=True,
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Creator of this Album share link",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
