# Generated by Django 3.1.3 on 2020-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_album_publicly_accessible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="publicly_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether this album is publicly accessible. If checked, this album is listed on the front page and accessible without authentication.",
            ),
        ),
    ]
