# Generated by Django 3.1.4 on 2020-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0005_auto_20201201_0312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="publicly_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Whether this album is publicly accessible. If checked, this album is listed on the front page and accessible without authentication. The photos within this album are not visible on the front page, however, they are publicly accessible with their link.",
            ),
        ),
    ]
