# Generated by Django 3.1.4 on 2020-12-27 22:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "defined_name",
                    models.CharField(
                        blank=True,
                        help_text="Name for this face. Ignored if a user is defined",
                        max_length=250,
                    ),
                ),
                (
                    "modify_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last modified time"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user that created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that whose face is represented by this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "face_data",
                    models.TextField(
                        help_text="Internal data used to recognize this face.",
                        max_length=5000,
                    ),
                ),
            ],
        ),
    ]
