# Generated by Django 3.1.4 on 2020-12-28 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("faces", "0001_squashed_0003_auto_20201227_2248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that created this object.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="face",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that whose face is represented by this object.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
